import .meta_sort
import .meta_symbol

def k_list : #SymbolList :=
[
    #symbol "#nilCharList" [%Char] [] %CharList,
    #symbol "#consCharList" [%Char] [%CharList, %Char] %CharList,
    #symbol "#epsilon" [%Char] [%CharList, %Char] %CharList,
    #symbol "#appendKCharList" [%Char] [%CharList, %CharList] %CharList,
    #symbol "#concat" [%Char] [%CharList, %CharList] %CharList,
    #symbol "#sort" [%Sort] [%String, %SortList] %Sort,
    #symbol "#nilSortList" [%Sort] [] %SortList,
    #symbol "#consSortList" [%Sort] [%Sort, %SortList] %SortList,
    #symbol "#appendSortList" [%Sort] [%SortList, %SortList] %SortList,
    #symbol "#inSortList" [%Sort] [%Sort, %Sort, %SortList] %Pattern,
    #symbol "#deleteSortList" [%Sort] [%Sort, %Sort, %SortList] %Sort,
    #symbol "#symbol" [] [%String, %SortList, %SortList, %Sort] %Symbol,
    #symbol "#getArgumentSorts" [] [%Symbol] %SortList,
    #symbol "#nilSymbolList" [%Symbol] [] %SymbolList,
    #symbol "#consSymbolList" [%Symbol] [%Symbol, %SymbolList] %SymbolList, 
    #symbol "#appendSymbolList" [%Symbol] [%SymbolList, %SymbolList] %SymbolList, 
    #symbol "#variable" [] [%String, %Sort] %Variable, 
    #symbol "#nilVariableList" [%Variable] [] %VariableList,
    #symbol "#consVariableList" [%Variable] [%Variable, %VariableList] %VariableList, 
    #symbol "#inSymbolList" [%Sort] [%Symbol, %SymbolList] %Pattern, 
    #symbol "#inVariableList" [%Sort] [%Variable, %VariableList] %Pattern, 
    #symbol "#deleteSymbolList" [] [%Symbol, %SymbolList] %SymbolList,
    #symbol "#'ceil" [] [%Sort, %Sort] %Symbol,
    #symbol "#appendVariableList" [%Variable] [%VariableList, %VariableList] %VariableList, 
    #symbol "#deleteVariableList" [] [%Variable, %VariableList] %VariableList,
    #symbol "#variableAsPattern" [] [%Variable] %Pattern,
    #symbol "#variablePattern" [] [%Variable] %Pattern,
    #symbol "#application" [] [%Symbol, %PatternList] %Pattern,
    #symbol "#and" [] [%Sort, %Pattern, %Pattern] %Pattern,
    #symbol "#not" [] [%Sort, %Pattern] %Pattern,
    #symbol "#exists" [] [%Sort, %Variable, %Pattern] %Pattern,
    #symbol "#or" [] [%Sort, %Pattern, %Pattern] %Pattern,
    #symbol "#implies" [] [%Sort, %Pattern, %Pattern] %Pattern,
    #symbol "#iff" [] [%Sort, %Pattern, %Pattern] %Pattern,
    #symbol "#forall" [] [%Sort, %Variable, %Pattern] %Pattern,
    #symbol "#ceil" [] [%Sort, %Sort, %Pattern] %Pattern,
    #symbol "#floor" [] [%Sort, %Sort, %Pattern] %Pattern,
    #symbol "#equals" [] [%Sort, %Sort, %Pattern, %Pattern] %Pattern,
    #symbol "#in" [] [%Sort, %Sort, %Pattern, %Pattern] %Pattern,
    #symbol "#top" [] [%Sort] %Pattern,
    #symbol "#bottom" [] [%Sort] %Pattern,
    #symbol "#nilPatternList" [%Sort] [] %PatternList,
    #symbol "#consPatternList" [%Sort] [%Pattern, %PatternList] %PatternList,
    #symbol "#appendPatternList" [%Sort] [%PatternList, %PatternList] %PatternList,
    #symbol "#inPatternList" [%Sort] [%Sort, %Pattern, %PatternList] %Sort,
    #symbol "#deletePatternList" [%Sort] [%Sort, %Pattern, %PatternList] %PatternList,
    #symbol "getFV" [] [%Pattern] %VariableList,
    #symbol "getFVFromPatterns" [] [%PatternList] %VariableList,
    #symbol "occursFree" [%Sort] [%Variable, %Pattern] %Sort,
    #symbol "freshName" [] [%PatternList] %String,
    #symbol "substitute" [] [%Variable, %Pattern, %Pattern] %Pattern,
    #symbol "substitutePatterns" [] [%Variable, %Pattern, %PatternList] %PatternList,
    #symbol "sortDeclared" [%Sort] [%Sort, %SortList] %Pattern,
    #symbol "sortsDeclared" [%Sort] [%SortList, %SortList] %Pattern,
    #symbol "symbolDeclared" [%Sort] [%Symbol, %SymbolList] %Pattern,
    #symbol "axiomDeclared" [%Sort] [%Pattern, %PatternList] %Pattern,
    #symbol "wellFormed" [%Sort] [%Pattern] %Sort,
    #symbol "wellFormedPatterns" [%Sort] [%PatternList] %Pattern,
    #symbol "getSortsFromPatterns" [] [%PatternList] %SortList,
    #symbol "provable" [%Sort] [%Pattern] %Pattern
]
